name: restart-hf-space-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '00 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements_restart_hf_space.txt

      - name: execute python workflows from bash script
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
        run: python3 ./restart_hf_space.py
